parameters:
#    home_index.example.class: Home\IndexBundle\Example

services:
#    home_index.example:
#        class: %home_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
